# Generated by Django 4.2.4 on 2023-08-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('return_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_level', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('return_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_level', models.PositiveIntegerField()),
            ],
        ),
    ]
